<?php

/**
 * Created by PhpStorm.
 * User: glpz
 * Date: 16/05/17
 * Time: 8:40
 */

namespace daxslab\contactform;

use yii\base\Module as BaseModule;
use yii\httpclient\Client;
use yii\web\NotFoundHttpException;

/**
 * Class Module
 * @package daxslab\cmsclient
 */
class Module extends BaseModule
{

    public $fromEmail;
    public $successMessage;
    public $errorMessage;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}
